### ISSUE TITLE
ESP01S GPIO2接地无法启动

### ISSUE THREAD

**Issue by itatboy** [hpencilb/HB-Arduino#1]
如题，未连接WIFI，GPIO2接地导致ESP01S启动失败的具体原因了解吗

**Comment by hpencilb** [comment]
可以参考一下[datasheet](https://github.com/hpencilb/HB-Arduino/blob/master/Notes/Data%20sheets/esp-01s_product_specification_zh_v1.0.pdf)，我实际用的电路里接了个1k的电阻上拉了GPIO2，启动和控制是正常的。

**Comment by itatboy** [comment]
感谢
